[package]
name = "d1-mini"
version = "0.1.0"
authors = ["Jesse Braham <jesse@beta7.io>"]
description = "A Board Support Package (BSP) which provides a type-safe API for the WEMOS/LOLIN D1 mini"
keywords = ["embedded-hal", "no-std", "xtensa"]
repository = "https://github.com/jessebraham/d1-mini"
readme = "README.md"
documentation = "https://docs.rs/d1-mini/"
edition = "2018"

[dependencies]
esp8266 = "0.0.4"
esp8266-hal = "0.1.0"
paste = "1.0.0"
