[package]
name = "d1-mini"
version = "0.1.0"
authors = ["Jesse Braham <jesse@beta7.io>"]
description = "A Board Support Package (BSP) which provides a type-safe API for the WEMOS/LOLIN D1 mini"
keywords = ["embedded-hal", "no-std", "xtensa"]
repository = "https://github.com/jessebraham/d1-mini"
readme = "README.md"
documentation = "https://docs.rs/d1-mini/"
edition = "2018"

[dependencies]
esp8266-hal = { git = "https://github.com/esp-rs/esp8266-hal", rev = "49b23f461f5654622948595912678be6121d90e9" }
paste = "1.0.0"

[dev-dependencies]
nb = "0.1.2"
panic-halt = "0.2.0"
xtensa-lx106-rt = { git = "https://github.com/icewind1991/xtensa-lx106-rt", rev = "2cc1e9b963ca2c2323a77562ad41ac620d8ae723" }

[profile.dev]
lto = true 
incremental = false
debug = false # debug adds frame pointers - which must be omitted
codegen-units = 1

[profile.release]
lto = true
incremental = false
debug = false # debug adds frame pointers - which must be omitted
codegen-units = 1
